# Generated by Django 3.1.7 on 2021-03-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='exam',
        ),
    ]
